In [15]:
##Import dataset
import numpy as np
import pandas as pd

dataset = pd.read_csv("DatasetClean.csv")
dataset.head()

2Grammed_APICalls_#10  2Grammed_APICalls_#102  2Grammed_APICalls_#105  \
0                      0                       0                       0   
1                      0                       0                       0   
2                      0                       0                       0   
3                      0                       0                       0   
4                      0                       0                       0   

   2Grammed_APICalls_#107  2Grammed_APICalls_#108  2Grammed_APICalls_#110  \
0                       0                       0                       0   
1                       0                       0                       0   
2                       0                       0                       0   
3                       0                       0                       0   
4                       0                       0                       0   

   2Grammed_APICalls_#111  2Grammed_APICalls_#114  2Grammed_APICalls_#126  \
0                       0                       0                       0   
1                       0                       0                       0   
2                       0                       0                       0   
3                       0                       0                       0   
4                       0                       0                       0   

   2Grammed_APICalls_#128  ...  Packet_Length_Std  Packet_Length_Variance  \
0                       0  ...               5880                 2954041   
1                       0  ...               5904                 2945087   
2                       0  ...               7895                 4000639   
3                       0  ...               7852                 3875751   
4                       0  ...               7087                 3528936   

   SYN_Flag_Count  Subflow_Bwd_Bytes  Subflow_Bwd_Packets  Subflow_Fwd_Bytes  \
0               2             208010                  238              22380   
1               3             237811                  264              23368   
2               3             458257                  439              27808   
3               3             403554                  410              32993   
4               4             334440                  344              27579   

   Subflow_Fwd_Packets  Total_Length_of_Bwd_Packets  URG_Flag_Count  Family  
0                  214                       208010               6   koler  
1                  222                       237811               6   koler  
2                  330                       458257               9   koler  
3                  316                       403554               8   koler  
4                  279                       334440               8   koler  

[5 rows x 461 columns]

In [16]:
##pemisahan atribut independen yaitu "Family"
x = dataset.drop(["Family"], axis=1)
x.head()

2Grammed_APICalls_#10  2Grammed_APICalls_#102  2Grammed_APICalls_#105  \
0                      0                       0                       0   
1                      0                       0                       0   
2                      0                       0                       0   
3                      0                       0                       0   
4                      0                       0                       0   

   2Grammed_APICalls_#107  2Grammed_APICalls_#108  2Grammed_APICalls_#110  \
0                       0                       0                       0   
1                       0                       0                       0   
2                       0                       0                       0   
3                       0                       0                       0   
4                       0                       0                       0   

   2Grammed_APICalls_#111  2Grammed_APICalls_#114  2Grammed_APICalls_#126  \
0                       0                       0                       0   
1                       0                       0                       0   
2                       0                       0                       0   
3                       0                       0                       0   
4                       0                       0                       0   

   2Grammed_APICalls_#128  ...  Packet_Length_Mean  Packet_Length_Std  \
0                       0  ...                4904               5880   
1                       0  ...                4699               5904   
2                       0  ...                6487               7895   
3                       0  ...                6469               7852   
4                       0  ...                6052               7087   

   Packet_Length_Variance  SYN_Flag_Count  Subflow_Bwd_Bytes  \
0                 2954041               2             208010   
1                 2945087               3             237811   
2                 4000639               3             458257   
3                 3875751               3             403554   
4                 3528936               4             334440   

   Subflow_Bwd_Packets  Subflow_Fwd_Bytes  Subflow_Fwd_Packets  \
0                  238              22380                  214   
1                  264              23368                  222   
2                  439              27808                  330   
3                  410              32993                  316   
4                  344              27579                  279   

   Total_Length_of_Bwd_Packets  URG_Flag_Count  
0                       208010               6  
1                       237811               6  
2                       458257               9  
3                       403554               8  
4                       334440               8  

[5 rows x 460 columns]

In [17]:
x.shape

(305, 460)

In [18]:
y = dataset["Family"]
y.head()

0    koler
1    koler
2    koler
3    koler
4    koler
Name: Family, dtype: object

In [19]:
##pembagian pertama 60% data training dan 40% data test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.40)

In [20]:
len(x_train)

183

In [21]:
len(x_test)

122

In [22]:
y_train.head()

67            feiwo
47         gooligan
246    fakejoboffer
42         mobidash
65           kemoge
Name: Family, dtype: object

In [23]:
y_test.head()

280      smssniffer
197      simplocker
34           pletor
28         RansomBO
118    AvForAndroid
Name: Family, dtype: object

In [24]:
###klasifikasi Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import r2_score

clf = GaussianNB()
clf.fit(x_train, y_train)

GaussianNB()

In [25]:
y_pred = clf.predict(x_test)

In [26]:
##klasifikasi data test
from time import time
start = time()
y_pred = clf.predict(x_test)
end = time()
result = end-start
print(y_pred)
print('Time = %f seconds' % result)

['plankton' 'penetho' 'pletor' 'gooligan' 'gooligan' 'FakeTaoBao'
 'fakejoboffer' 'youmi' 'fakejoboffer' 'fakemart' 'charger'
 'android.spy.277' 'avpass' 'plankton' 'jisut' 'zsone' 'fakeapp' 'ewind'
 'AndroidDefender' 'jifake' 'ewind' 'plankton' 'mazarbot' 'ewind'
 'AvForAndroid' 'ewind' 'nandrobox' 'youmi' 'FakeTaoBao' 'zsone' 'charger'
 'fakejoboffer' 'AndroidDefender' 'mazarbot' 'fakejoboffer' 'jifake'
 'smssniffer' 'jisut' 'ewind' 'gooligan' 'FakeTaoBao' 'ewind'
 'wannalocker' 'fakemart' 'gooligan' 'AndroidDefender' 'AndroidDefender'
 'porndroid' 'charger' 'wannalocker' 'ewind' 'AvForAndroid' 'AvForAndroid'
 'jisut' 'fakejoboffer' 'avpass' 'feiwo' 'svpeng' 'fakejoboffer'
 'mobidash' 'dowgin' 'fakemart' 'porndroid' 'jisut' 'fakemart' 'fakeinst'
 'jisut' 'wannalocker' 'svpeng' 'porndroid' 'AvForAndroid' 'jisut'
 'mazarbot' 'beanbot' 'jisut' 'charger' 'fakeinst' 'gooligan' 'jisut'
 'kemoge' 'kemoge' 'porndroid' 'mobidash' 'fakemart' 'mazarbot' 'kemoge'
 'fakeapp' 'FakeTaoBao' 'wannalo

In [27]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print('========================Confusion Metrix :========================')
print(confusion_matrix(y_test, y_pred))
print()
print('=====================classification_report :======================')
print(classification_report(y_test, y_pred))
print('========================Accuracy Score :==========================')
print('60:40')
print(accuracy_score(y_test, y_pred))
print('============================ Timer :==============================')
print('Timer = %f seconds' % result)

========================Confusion Metrix :========================
[[4 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

=====================classification_report :======================
                 precision    recall  f1-score   support

AndroidDefender       0.67      0.67      0.67         6
   AvForAndroid       0.00      0.00      0.00         5
     FakeTaoBao       0.14      1.00      0.25         1
       RansomBO       1.00      0.17      0.29         6
android.spy.277       0.00      0.00      0.00         3
         avpass       0.00      0.00      0.00         3
        beanbot       1.00      0.40      0.57         5
          biige       0.00      0.00      0.00         2
        charger       0.60      0.75      0.67         4
         dowgin       1.00      1.00      1.00         1
          ewind       0.12      0.50      0.20         2
        fakeapp       0.00      0.00      0.00         1
   

C:\Users\RAMADAN PRATAMA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [28]:
##pembagian pertama 70% data training dan 30% data test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30)

In [29]:
len(x_train)

213

In [30]:
len(x_test)

92

In [31]:
###klasifikasi Naive Bayes
clf = GaussianNB()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

##klasifikasi data test
from time import time
start = time()
y_pred = clf.predict(x_test)
end = time()
result = end-start
print(y_pred)
print('Time = %f seconds' % result)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print('========================Confusion Metrix :========================')
print(confusion_matrix(y_test, y_pred))
print()
print('=====================classification_report :======================')
print(classification_report(y_test, y_pred))
print('========================Accuracy Score :==========================')
print('70:30')
print(accuracy_score(y_test, y_pred))
print('============================ Timer :==============================')
print('Timer = %f seconds' % result)

['feiwo' 'fakeinst' 'mobidash' 'FakeTaoBao' 'FakeTaoBao' 'shuanet'
 'RansomBO' 'fakemart' 'charger' 'jisut' 'AvForAndroid' 'charger' 'pletor'
 'jisut' 'fakeinst' 'fakemart' 'AndroidDefender' 'jisut' 'jisut'
 'porndroid' 'charger' 'porndroid' 'jifake' 'jisut' 'dowgin'
 'AndroidDefender' 'nandrobox' 'jisut' 'fakemart' 'smssniffer' 'pletor'
 'smssniffer' 'ewind' 'youmi' 'AndroidDefender' 'fakejoboffer' 'ewind'
 'smssniffer' 'jisut' 'svpeng' 'zsone' 'virusshield' 'nandrobox' 'penetho'
 'beanbot' 'jisut' 'beanbot' 'ewind' 'ewind' 'kemoge' 'nandrobox'
 'fakejoboffer' 'shuanet' 'jisut' 'FakeTaoBao' 'porndroid' 'smssniffer'
 'fakeav' 'FakeTaoBao' 'koler' 'zsone' 'virusshield' 'feiwo'
 'fakejoboffer' 'RansomBO' 'penetho' 'fakejoboffer' 'fakeinst' 'jifake'
 'kemoge' 'smssniffer' 'gooligan' 'jifake' 'dowgin' 'nandrobox'
 'fakejoboffer' 'jifake' 'fakejoboffer' 'RansomBO' 'charger' 'shuanet'
 'fakemart' 'charger' 'porndroid' 'jifake' 'porndroid' 'kemoge' 'dowgin'
 'charger' 'ewind' 'jifake' 'ewind'

C:\Users\RAMADAN PRATAMA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[1 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [1 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 2]]

=====================classification_report :======================
                 precision    recall  f1-score   support

AndroidDefender       0.33      0.25      0.29         4
   AvForAndroid       0.00      0.00      0.00         2
     FakeTaoBao       0.25      0.50      0.33         2
       RansomBO       0.67      0.67      0.67         3
android.spy.277       0.00      0.00      0.00         1
         avpass       0.00      0.00      0.00         3
        beanbot       0.00      0.00      0.00         1
          biige       0.00      0.00      0.00         2
        charger       0.50      1.00      0.67         3
         dowgin       0.67      0.67      0.67         3
          ewind       0.00      0.00      0.00         1
        fakeapp       0.00      0.00      0.00         2
         fakeav       0.00      0.00      0.00         3
       fakein

C:\Users\RAMADAN PRATAMA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
##pembagian ketiga 80% data training dan 20% data test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

In [33]:
len(x_train)

244

In [34]:
len(x_test)

61

In [35]:


###klasifikasi Naive Bayes
clf = GaussianNB()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

##klasifikasi data test
from time import time
start = time()
y_pred = clf.predict(x_test)
end = time()
result = end-start
print(y_pred)
print('Time = %f seconds' % result)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print('========================Confusion Metrix :========================')
print(confusion_matrix(y_test, y_pred))
print()
print('=====================classification_report :======================')
print(classification_report(y_test, y_pred))
print('========================Accuracy Score :==========================')
print('80:20')
print(accuracy_score(y_test, y_pred))
print('============================ Timer :==============================')
print('Timer = %f seconds' % result)

['jifake' 'jisut' 'porndroid' 'pletor' 'wannalocker' 'ewind' 'jisut'
 'zsone' 'jifake' 'ewind' 'FakeTaoBao' 'avpass' 'android.spy.277' 'zsone'
 'porndroid' 'beanbot' 'AndroidDefender' 'ewind' 'RansomBO' 'mazarbot'
 'fakemart' 'pletor' 'nandrobox' 'AvForAndroid' 'charger' 'beanbot'
 'AndroidDefender' 'mobidash' 'FakeTaoBao' 'fakemart' 'fakejoboffer'
 'mobidash' 'fakeinst' 'fakeapp' 'FakeTaoBao' 'fakemart' 'jisut' 'ewind'
 'fakeapp' 'plankton' 'charger' 'jisut' 'fakemart' 'biige' 'koler'
 'fakeav' 'svpeng' 'shuanet' 'jisut' 'fakejoboffer' 'ewind' 'svpeng'
 'mazarbot' 'jisut' 'jisut' 'fakeav' 'jifake' 'youmi' 'dowgin' 'fakemart'
 'mazarbot']
Time = 0.020942 seconds
========================Confusion Metrix :========================
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

=====================classification_report :======================
                 precision    recall  f1-score   support

AndroidDefender 

C:\Users\RAMADAN PRATAMA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\RAMADAN PRATAMA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [36]:
##pembagian keempat 90% data training dan 10% data test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.10)


In [37]:
len(x_train)

274

In [38]:
len(x_test)

31

In [39]:

###klasifikasi Naive Bayes
clf = GaussianNB()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

##klasifikasi data test
from time import time
start = time()
y_pred = clf.predict(x_test)
end = time()
result = end-start
print(y_pred)
print('Time = %f seconds' % result)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print('========================Confusion Metrix :========================')
print(confusion_matrix(y_test, y_pred))
print()
print('=====================classification_report :======================')
print(classification_report(y_test, y_pred))
print('========================Accuracy Score :==========================')
print('90:10')
print(accuracy_score(y_test, y_pred))
print('============================ Timer :==============================')
print('Timer = %f seconds' % result)

['mobidash' 'fakejoboffer' 'fakemart' 'fakemart' 'fakeav'
 'AndroidDefender' 'smssniffer' 'smssniffer' 'wannalocker' 'fakejoboffer'
 'fakemart' 'dowgin' 'lockerpin' 'porndroid' 'dowgin' 'nandrobox'
 'shuanet' 'mazarbot' 'ewind' 'nandrobox' 'svpeng' 'koler' 'jisut'
 'svpeng' 'svpeng' 'fakemart' 'fakeav' 'android.spy.277' 'smssniffer'
 'RansomBO' 'mazarbot']
Time = 0.015962 seconds
========================Confusion Metrix :========================
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

C:\Users\RAMADAN PRATAMA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\RAMADAN PRATAMA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
