In [1]:
##Import dataset
import numpy as np
from numpy import mean
import pandas as pd

dataset = pd.read_csv("249_fiture_usage.csv")
dataset.head()


2Grammed_APICalls_#102  2Grammed_APICalls_#144  2Grammed_APICalls_#148  \
0                       0                       0                       0   
1                       0                       0                       0   
2                       0                       0                       0   
3                       0                       0                       0   
4                       0                       0                       0   

   2Grammed_APICalls_#157  2Grammed_APICalls_#161  2Grammed_APICalls_#168  \
0                       0                       0                       0   
1                       0                       0                       0   
2                       0                       0                       0   
3                       0                       0                       0   
4                       0                       0                       0   

   2Grammed_APICalls_#170  2Grammed_APICalls_#173  2Grammed_APICalls_#201  \
0                       0                       0                       0   
1                       0                       0                       0   
2                       0                       0                       0   
3                       0                       0                       0   
4                       0                       0                       0   

   2Grammed_APICalls_#209  ...  Packet_Length_Mean  Packet_Length_Std  \
0                       0  ...                4904               5880   
1                       0  ...                4699               5904   
2                       0  ...                6487               7895   
3                       0  ...                6469               7852   
4                       0  ...                6052               7087   

   Packet_Length_Variance  SYN_Flag_Count  Subflow_Bwd_Bytes  \
0                 2954041               2             208010   
1                 2945087               3             237811   
2                 4000639               3             458257   
3                 3875751               3             403554   
4                 3528936               4             334440   

   Subflow_Bwd_Packets  Subflow_Fwd_Bytes  Subflow_Fwd_Packets  \
0                  238              22380                  214   
1                  264              23368                  222   
2                  439              27808                  330   
3                  410              32993                  316   
4                  344              27579                  279   

   Total_Length_of_Bwd_Packets  Family  
0                       208010   koler  
1                       237811   koler  
2                       458257   koler  
3                       403554   koler  
4                       334440   koler  

[5 rows x 250 columns]

In [2]:
##pemisahan atribut independen yaitu "Family"
x = dataset.drop(["Family"], axis=1)
x.head()

2Grammed_APICalls_#102  2Grammed_APICalls_#144  2Grammed_APICalls_#148  \
0                       0                       0                       0   
1                       0                       0                       0   
2                       0                       0                       0   
3                       0                       0                       0   
4                       0                       0                       0   

   2Grammed_APICalls_#157  2Grammed_APICalls_#161  2Grammed_APICalls_#168  \
0                       0                       0                       0   
1                       0                       0                       0   
2                       0                       0                       0   
3                       0                       0                       0   
4                       0                       0                       0   

   2Grammed_APICalls_#170  2Grammed_APICalls_#173  2Grammed_APICalls_#201  \
0                       0                       0                       0   
1                       0                       0                       0   
2                       0                       0                       0   
3                       0                       0                       0   
4                       0                       0                       0   

   2Grammed_APICalls_#209  ...  Max_Packet_Length  Packet_Length_Mean  \
0                       0  ...              15128                4904   
1                       0  ...              15659                4699   
2                       0  ...              20233                6487   
3                       0  ...              20357                6469   
4                       0  ...              18209                6052   

   Packet_Length_Std  Packet_Length_Variance  SYN_Flag_Count  \
0               5880                 2954041               2   
1               5904                 2945087               3   
2               7895                 4000639               3   
3               7852                 3875751               3   
4               7087                 3528936               4   

   Subflow_Bwd_Bytes  Subflow_Bwd_Packets  Subflow_Fwd_Bytes  \
0             208010                  238              22380   
1             237811                  264              23368   
2             458257                  439              27808   
3             403554                  410              32993   
4             334440                  344              27579   

   Subflow_Fwd_Packets  Total_Length_of_Bwd_Packets  
0                  214                       208010  
1                  222                       237811  
2                  330                       458257  
3                  316                       403554  
4                  279                       334440  

[5 rows x 249 columns]

In [3]:
y = dataset["Family"]
y.head()

0    koler
1    koler
2    koler
3    koler
4    koler
Name: Family, dtype: object

In [4]:
##pembagian pertama 60% data training dan 40% data test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1)

In [5]:
len(x_train)

274

In [6]:
len(x_test)

31

In [7]:
y_train.head()

234    AndroidDefender
222              feiwo
82              avpass
268             jifake
44            mobidash
Name: Family, dtype: object

In [8]:
y_test.head()

251         penetho
60           kemoge
37        porndroid
102    fakejoboffer
27         RansomBO
Name: Family, dtype: object

In [9]:
###klasifikasi Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import r2_score

###klasifikasi Naive Bayes
clf = GaussianNB()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [10]:
##klasifikasi data test
from time import time
start = time()
y_pred = clf.predict(x_test)
end = time()
result = end-start
print(y_pred)
print('Time = %f seconds' % result)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print('========================Confusion Metrix :========================')
print(confusion_matrix(y_test, y_pred))
print()
print('=====================classification_report :======================')
print(classification_report(y_test, y_pred))
print('========================Accuracy Score :==========================')
print(accuracy_score(y_test, y_pred))
print('============================ Timer :==============================')
print('Timer = %f seconds' % result)

['penetho' 'beanbot' 'smssniffer' 'fakejoboffer' 'RansomBO' 'nandrobox'
 'penetho' 'fakemart' 'zsone' 'fakemart' 'mazarbot' 'fakejoboffer'
 'RansomBO' 'zsone' 'jisut' 'jisut' 'fakeav' 'shuanet' 'koler'
 'smssniffer' 'fakemart' 'AndroidDefender' 'android.spy.277' 'kemoge'
 'avpass' 'porndroid' 'AndroidDefender' 'beanbot' 'kemoge' 'fakemart'
 'RansomBO']
Time = 0.027927 seconds
========================Confusion Metrix :========================
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 

C:\Users\RAMADAN PRATAMA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\RAMADAN PRATAMA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
from sklearn.model_selection import KFold, cross_val_score

#create model
###model = GaussianNB()

#evaluate model
scores = cross_val_score(clf, x, y, scoring = 'accuracy', cv = 10)
#report performance

print(scores)
print('Accuracy: %.3f' %(mean(scores)))

C:\Users\RAMADAN PRATAMA\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"


[0.22580645 0.29032258 0.22580645 0.22580645 0.41935484 0.3
 0.26666667 0.43333333 0.3        0.3       ]
Accuracy: 0.299
